# Generated by Django 4.1 on 2022-10-08 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(help_text='appointment ID', primary_key=True, serialize=False)),
                ('begin_at', models.DateTimeField()),
                ('category', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('subject', models.CharField(max_length=50)),
                ('authority', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(help_text='Post ID', primary_key=True, serialize=False)),
                ('is_directory', models.BooleanField(default=False)),
                ('file_name', models.CharField(max_length=50)),
                ('file_content', models.JSONField(default=dict)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('parent_id', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.template')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(help_text='symptom ID', primary_key=True, serialize=False)),
                ('s_code', models.CharField(max_length=50)),
                ('s_onset', models.DateTimeField()),
                ('s_severity', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('appointment_id', models.ForeignKey(blank=True, db_column='appointment_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.appointment')),
                ('doctor_id', models.ForeignKey(blank=True, db_column='doctor_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symptom_publisher', to='api.user')),
                ('patient_id', models.ForeignKey(blank=True, db_column='patient_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symptom_patient', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Prescript',
            fields=[
                ('id', models.BigAutoField(help_text='prescript ID', primary_key=True, serialize=False)),
                ('medicine_code', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('medicine_unit', models.CharField(max_length=50)),
                ('medicine_begin_time', models.DateTimeField()),
                ('medicine_end_time', models.DateTimeField()),
                ('medicine_dose_unit', models.CharField(max_length=50)),
                ('medicine_dose', models.IntegerField()),
                ('medicine_usage', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=500)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('appointment_id', models.ForeignKey(blank=True, db_column='appointment_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.appointment')),
                ('doctor_id', models.ForeignKey(blank=True, db_column='doctor_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescript_publisher', to='api.user')),
                ('patient_id', models.ForeignKey(blank=True, db_column='patient_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescript_patient', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(help_text='diagnosis ID', primary_key=True, serialize=False)),
                ('begin_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('diag_type', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=500)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('appointment_id', models.ForeignKey(blank=True, db_column='appointment_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.appointment')),
                ('doctor_id', models.ForeignKey(blank=True, db_column='doctor_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagonsis_publisher', to='api.user')),
                ('patient_id', models.ForeignKey(blank=True, db_column='patient_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_patient', to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_id',
            field=models.ForeignKey(blank=True, db_column='doctor_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='api.user'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_id',
            field=models.ForeignKey(blank=True, db_column='patient_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='api.user'),
        ),
    ]
