# Generated by Django 4.1.5 on 2023-01-11 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescript',
            name='appointment_id',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='appointment_id',
        ),
        migrations.AddField(
            model_name='prescript',
            name='diagnosis_id',
            field=models.ForeignKey(blank=True, db_column='diagnosis_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.diagnosis'),
        ),
        migrations.AddField(
            model_name='symptom',
            name='diagnosis_id',
            field=models.ForeignKey(blank=True, db_column='diagnosis_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.diagnosis'),
        ),
    ]
