# Generated by Django 4.1 on 2022-11-09 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user_idx', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.user')),
                ('subject', models.CharField(max_length=50)),
                ('room', models.CharField(default=None, max_length=50, null=True)),
                ('dept_idx', models.IntegerField(default=None, null=True)),
                ('sup_idx', models.IntegerField(default=None, null=True)),
            ],
            bases=('api.user',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user_idx', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.user')),
                ('doc_idx', models.IntegerField(default=0)),
                ('is_admission', models.BooleanField(default=False)),
                ('room', models.CharField(max_length=50)),
            ],
            bases=('api.user',),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor_id',
            field=models.ForeignKey(blank=True, db_column='doctor_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_ref_id', to='api.user'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_id',
            field=models.ForeignKey(blank=True, db_column='patient_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_ref_id', to='api.user'),
        ),
    ]
