# Generated by Django 4.1 on 2022-11-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescript',
            name='named_entity',
            field=models.JSONField(default=dict),
        ),
    ]
