# Generated by Django 4.1.5 on 2023-01-11 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_prescript_medicine_name_alter_prescript_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='begin_time',
            new_name='begin_at',
        ),
        migrations.RenameField(
            model_name='diagnosis',
            old_name='end_time',
            new_name='end_at',
        ),
    ]
