# Generated by Django 4.1.5 on 2023-01-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_begin_time_diagnosis_begin_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='end_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
