# Generated by Django 4.1.5 on 2023-01-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_diagnosis_end_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='id',
            field=models.BigAutoField(help_text='diagnosis ID', primary_key=True, serialize=False),
        ),
    ]
